timeout: 15m
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'rusty-build', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'rusty-build', 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/rusty-microservice:$REVISION_ID' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'rusty-build', 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/rusty-microservice:latest' ]
images:
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/rusty-microservice'
