timeout: 15m
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/rusty-build', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'gcr.io/$PROJECT_ID/rusty-build', 'gcr.io/$PROJECT_ID/rusty-microservice:$REVISION_ID' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'gcr.io/$PROJECT_ID/rusty-build', 'gcr.io/$PROJECT_ID/rusty-microservice:latest' ]
images:
- 'gcr.io/$PROJECT_ID/rusty-microservice'
